#!/bin/bash

# BUYNT CHAT SYSTEM - USEFUL COMMANDS
# Quick reference for common tasks

echo "════════════════════════════════════════════════════════════════"
echo "🔧 BUYNT CHAT SYSTEM - USEFUL COMMANDS"
echo "════════════════════════════════════════════════════════════════"
echo ""

# ==================== DEVELOPMENT ====================
echo "📝 DEVELOPMENT"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "# Start dev server"
echo "npm run dev"
echo ""
echo "# Build for production"
echo "npm run build"
echo ""
echo "# Preview production build locally"
echo "npm run preview"
echo ""
echo "# Lint code"
echo "npm run lint"
echo ""

# ==================== DATABASE ====================
echo "🗄️  DATABASE SETUP"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "# Option 1: Execute migration via Supabase CLI"
echo "npm install -D @supabase/cli"
echo "npx supabase db push"
echo ""
echo "# Option 2: Manual via Dashboard"
echo "# 1. Go to https://app.supabase.com"
echo "# 2. SQL Editor → Create new query"
echo "# 3. Copy entire: supabase/migrations/20250111_chat_system.sql"
echo "# 4. Click RUN"
echo ""
echo "# Option 3: Via deployment script"
echo "bash deploy-chat.sh"
echo ""
echo "# Verify tables exist"
echo "# In Supabase Dashboard → Table Editor → Check for:"
echo "# - conversations"
echo "# - messages"
echo "# - message_attachments"
echo "# - user_blocks"
echo "# - notifications"
echo ""

# ==================== REALTIME ====================
echo "⚡ ENABLE REALTIME"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "# Via Supabase CLI:"
echo "npx supabase realtime add --schema public --table conversations"
echo "npx supabase realtime add --schema public --table messages"
echo "npx supabase realtime add --schema public --table notifications"
echo ""
echo "# Via Dashboard:"
echo "# 1. Go to https://app.supabase.com → Project → Replication"
echo "# 2. Toggle ON for:"
echo "#    - conversations"
echo "#    - messages"
echo "#    - notifications"
echo ""

# ==================== TESTING ====================
echo "🧪 TESTING"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "# Run Playwright E2E tests"
echo "npm install -D @playwright/test"
echo "npx playwright test tests/chat.spec.ts"
echo ""
echo "# Manual test: Run 2 instances"
echo "# Terminal 1: npm run dev"
echo "# Browser 1: User A (email1@test.com)"
echo "# Browser 2: User B (email2@test.com)"
echo "# User B contacts User A → Chat opens"
echo ""

# ==================== DEBUGGING ====================
echo "🐛 DEBUGGING"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "# Check browser console for logs"
echo "F12 → Console → Look for chatService logs"
echo ""
echo "# Check TypeScript errors"
echo "npm run build  # Will show any TS errors"
echo ""
echo "# Check Supabase logs"
echo "Dashboard → Logs → Search for RPC function calls"
echo ""
echo "# Test RPC function directly"
echo "# Go to Supabase SQL Editor and run:"
echo "SELECT * FROM get_or_create_conversation('product-id-here'::uuid);"
echo ""

# ==================== FILE STRUCTURE ====================
echo "📁 KEY FILES"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "Backend:"
echo "  supabase/migrations/20250111_chat_system.sql      SQL Schema"
echo ""
echo "Frontend - Pages:"
echo "  src/pages/Messages.tsx                            Conversation list"
echo "  src/pages/MessageDetail.tsx                       Chat interface"
echo ""
echo "Frontend - Services:"
echo "  src/services/chatService.ts                       RPC + Realtime"
echo "  src/services/types.ts                             Interfaces"
echo ""
echo "Frontend - Components:"
echo "  src/components/chat/MessageBubble.tsx             Message display"
echo "  src/components/chat/MessageInput.tsx              Send input"
echo ""
echo "Frontend - Hooks:"
echo "  src/hooks/useChat.ts                              State management"
echo ""
echo "Routes:"
echo "  src/App.tsx                                       Router config"
echo ""

# ==================== DOCUMENTATION ====================
echo "📚 DOCUMENTATION"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "Quick Start:     bash QUICK_START.sh"
echo "Setup Guide:     cat CHAT_SETUP_GUIDE.md"
echo "System Docs:     cat CHAT_SYSTEM_GUIDE.md"
echo "Types Ref:       cat docs/TYPES_REFERENCE.md"
echo "Change Log:      cat CHANGELOG.md"
echo "Executive:       cat EXECUTIVE_SUMMARY.md"
echo "Inventory:       cat FILE_INVENTORY.md"
echo ""

# ==================== GIT ====================
echo "📦 GIT COMMANDS"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "# View changes"
echo "git diff src/pages/Messages.tsx"
echo ""
echo "# Stage changes"
echo "git add ."
echo ""
echo "# Commit"
echo "git commit -m 'feat: implement chat system with Realtime'"
echo ""
echo "# View files modified"
echo "git status"
echo ""

# ==================== DEPLOYMENT ====================
echo "🚀 DEPLOYMENT"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "# Pre-deploy checks"
echo "npm run build                                    Build without errors"
echo "npm run lint                                     No lint errors"
echo ""
echo "# Deploy frontend"
echo "# Vercel: git push (auto-deploy on main)"
echo "# Netlify: npm run build → drag dist/ folder"
echo "# AWS: amplify push"
echo ""
echo "# Deploy backend (Supabase)"
echo "# Already deployed when you ran the migration"
echo "# Just ensure env vars are correct in production"
echo ""
echo "# Check production deployment"
echo "# 1. Open your live site"
echo "# 2. Go to /messages"
echo "# 3. Verify chat works"
echo ""

# ==================== ENVIRONMENT VARIABLES ====================
echo "🔑 ENVIRONMENT VARIABLES"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo ".env (dev):"
echo "  VITE_SUPABASE_URL=https://xxx.supabase.co"
echo "  VITE_SUPABASE_ANON_KEY=eyJxxx..."
echo ""
echo ".env.production (live):"
echo "  VITE_SUPABASE_URL=https://xxx.supabase.co       (prod project)"
echo "  VITE_SUPABASE_ANON_KEY=eyJxxx...                (prod key)"
echo ""

# ==================== TROUBLESHOOTING ====================
echo "🆘 QUICK TROUBLESHOOTING"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "# 'RLS policy violation' error"
echo "→ Migración SQL incompleta. Revisa que se ejecutó todo."
echo ""
echo "# 'No se abre el chat desde Contactar'"
echo "→ Realtime no está habilitado. Check Replication en Dashboard."
echo ""
echo "# 'Mensajes no aparecen en tiempo real'"
echo "→ F12 → Console → busca errores de Supabase"
echo ""
echo "# 'Cannot find module error'"
echo "→ npm install"
echo ""
echo "# 'Build error with TypeScript'"
echo "→ npm run build shows what's wrong"
echo ""

# ==================== USEFUL LINKS ====================
echo "🔗 USEFUL LINKS"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "Supabase Dashboard:     https://app.supabase.com"
echo "Supabase Realtime:      https://supabase.com/docs/guides/realtime"
echo "Supabase RLS:           https://supabase.com/docs/guides/auth/row-level-security"
echo "React Docs:             https://react.dev"
echo "Tailwind CSS:           https://tailwindcss.com"
echo ""

# ==================== MONITORING ====================
echo "📊 MONITORING POST-LAUNCH"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "# Check chat usage"
echo "# Supabase Dashboard → Logs → Search 'chat'"
echo ""
echo "# Monitor performance"
echo "# Browser DevTools → Performance tab → Record interaction"
echo ""
echo "# Track errors"
echo "# Add error tracking (Sentry, LogRocket, etc.)"
echo ""

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "💡 For detailed info, check the documentation:"
echo ""
echo "   bash QUICK_START.sh"
echo "   cat CHAT_SETUP_GUIDE.md"
echo "   cat docs/TYPES_REFERENCE.md"
echo "════════════════════════════════════════════════════════════════"
echo ""
